#:schema node_modules/wrangler/config-schema.json
name = "discord-bot-cloudflare-ai-challenge"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[limits]
cpu_ms = 10

# [ai]
# binding = "AI"
